const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { URL } = require('url');
const { Pool } = require('pg');

const PORT = Number(process.env.PORT) || 5001;
const ROOT = __dirname, PUBLIC = path.join(ROOT, 'public'), UPLOADS = path.join(ROOT, 'uploads');
fs.mkdirSync(UPLOADS, { recursive: true });
const pool = new Pool({
  host: process.env.DB_HOST || 'localhost', port: Number(process.env.DB_PORT) || 5432,
  database: process.env.DB_NAME || 'vodolaz', user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres'
});
const ROLES = ['common', 'role1', 'role2', 'role3'];
const ROLE_NAMES = { common: 'Общие', role1: 'Роль1', role2: 'Роль2', role3: 'Роль3' };
const id = (p) => `${p}_${crypto.randomUUID()}`;
const now = () => new Date();
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.pbkdf2Sync(password, salt, 120000, 64, 'sha512').toString('hex')}`; }
function verifyPassword(password, value) { const [salt, hash] = String(value || '').split(':'); if (!salt || !hash) return false; const check = crypto.pbkdf2Sync(password, salt, 120000, 64, 'sha512').toString('hex'); try { return crypto.timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(check, 'hex')); } catch { return false; } }
function safeName(name) { return String(name || 'file').replace(/[^a-zA-Zа-яА-ЯёЁ0-9._-]/g, '_').slice(-120); }
function send(res, status, data, type = 'application/json; charset=utf-8') { res.writeHead(status, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(type.includes('json') ? JSON.stringify(data) : data); }
function parseBody(req) { return new Promise((resolve, reject) => { let body = ''; req.on('data', c => { body += c; if (body.length > 15 * 1024 * 1024) { reject(new Error('Слишком большой запрос')); req.destroy(); } }); req.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('Некорректные данные')); } }); req.on('error', reject); }); }
function publicUser(u) { return { id: u.id, firstName: u.first_name, lastName: u.last_name, email: u.email, phone: u.phone, role: u.role, createdAt: u.created_at }; }
async function auth(req) { const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); if (!token) return null; const r = await pool.query('select u.* from sessions s join users u on u.id=s.user_id where s.token=$1 and s.expires_at > now()', [token]); return r.rows[0] || null; }
async function initDb() {
  await pool.query(`create table if not exists users (id text primary key, first_name text not null, last_name text not null default '', email text not null unique, phone text not null default '', password_hash text not null, role text not null default 'common' check(role in ('admin','common','role1','role2','role3')), created_at timestamptz not null default now());
    create table if not exists sessions (token text primary key, user_id text not null references users(id) on delete cascade, expires_at timestamptz not null);
    create table if not exists materials (id text primary key, title text not null, description text not null default '', access_role text not null check(access_role in ('common','role1','role2','role3')), type text not null default 'file', url text not null, created_at timestamptz not null default now());
    create table if not exists applications (id text primary key, name text not null, phone text not null default '', email text not null default '', service text not null default '', comment text not null default '', status text not null default 'Новая', created_at timestamptz not null default now());`);
  const email = process.env.ADMIN_EMAIL || 'admin@albakor.local', password = process.env.ADMIN_PASSWORD || 'Albakor2026!';
  const found = await pool.query('select id from users where email=$1', [email]);
  if (!found.rowCount) { await pool.query('insert into users(id,first_name,last_name,email,password_hash,role) values($1,$2,$3,$4,$5,$6)', ['user_admin', 'Администратор', 'Альбакор', email, hashPassword(password), 'admin']); console.log(`Создан администратор: ${email} / ${password}`); }
}
async function api(req, res, url) {
  const p = url.pathname, method = req.method;
  try {
    if (method === 'GET' && p === '/api/programs') return send(res, 200, []);
    if (method === 'POST' && p === '/api/register') { const b = await parseBody(req), email = String(b.email || '').trim().toLowerCase(); if (!b.firstName || !email || String(b.password || '').length < 6) return send(res, 400, { error: 'Укажите имя, e-mail и пароль не короче 6 символов' }); const u = { id: id('user'), firstName: String(b.firstName).trim(), lastName: String(b.lastName || '').trim(), email, phone: String(b.phone || '').trim(), password: String(b.password) }; try { await pool.query('insert into users(id,first_name,last_name,email,phone,password_hash,role) values($1,$2,$3,$4,$5,$6,$7)', [u.id,u.firstName,u.lastName,u.email,u.phone,hashPassword(u.password),'common']); } catch (e) { if (e.code === '23505') return send(res,409,{error:'Пользователь с таким e-mail уже существует'}); throw e; } const t = crypto.randomBytes(32).toString('hex'); await pool.query('insert into sessions(token,user_id,expires_at) values($1,$2,$3)',[t,u.id,new Date(Date.now()+7*864e5)]); return send(res,201,{token:t,user:{...u,role:'common'}}); }
    if (method === 'POST' && p === '/api/login') { const b=await parseBody(req), email=String(b.email||'').trim().toLowerCase(); const r=await pool.query('select * from users where email=$1',[email]), u=r.rows[0]; if(!u || !verifyPassword(String(b.password||''),u.password_hash)) return send(res,401,{error:'Неверный e-mail или пароль'}); const t=crypto.randomBytes(32).toString('hex'); await pool.query('delete from sessions where expires_at <= now()'); await pool.query('insert into sessions(token,user_id,expires_at) values($1,$2,$3)',[t,u.id,new Date(Date.now()+7*864e5)]); return send(res,200,{token:t,user:publicUser(u)}); }
    if (method === 'POST' && p === '/api/logout') { const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); if(t) await pool.query('delete from sessions where token=$1',[t]); return send(res,200,{ok:true}); }
    if (method === 'POST' && p === '/api/applications') { const b=await parseBody(req); if(!b.name || (!b.phone && !b.email)) return send(res,400,{error:'Укажите имя и телефон или e-mail'}); await pool.query('insert into applications(id,name,phone,email,service,comment) values($1,$2,$3,$4,$5,$6)',[id('app'),String(b.name),String(b.phone||''),String(b.email||''),String(b.service||''),String(b.comment||'')]); return send(res,201,{ok:true}); }
    const user = await auth(req);
    if (method === 'GET' && p === '/api/me') { if(!user) return send(res,401,{error:'Требуется авторизация'}); const values=user.role==='admin'?[]:[user.role]; const q=user.role==='admin'?'select * from materials order by created_at desc':'select * from materials where access_role in (\'common\',$1) order by created_at desc'; const materials=(await pool.query(q,values)).rows; return send(res,200,{user:publicUser(user),roleNames:ROLE_NAMES,materials}); }
    if (p.startsWith('/api/admin/')) { if(!user || user.role!=='admin') return send(res,403,{error:'Доступ только для администратора'}); if(method==='GET' && p==='/api/admin/dashboard') { const [users,materials,apps]=await Promise.all([pool.query("select * from users where role <> 'admin' order by created_at desc"),pool.query('select * from materials order by created_at desc'),pool.query('select * from applications order by created_at desc')]); return send(res,200,{users:users.rows.map(publicUser),materials:materials.rows,applications:apps.rows,roles:ROLES.map(value=>({value,label:ROLE_NAMES[value]}))}); }
      let match=p.match(/^\/api\/admin\/users\/([^/]+)\/role$/); if(method==='PUT' && match) { const b=await parseBody(req); if(!ROLES.includes(b.role)) return send(res,400,{error:'Некорректная роль'}); const r=await pool.query("update users set role=$1 where id=$2 and role <> 'admin' returning *",[b.role,match[1]]); if(!r.rowCount) return send(res,404,{error:'Пользователь не найден'}); return send(res,200,{user:publicUser(r.rows[0])}); }
      if(method==='POST' && p==='/api/admin/materials') { const b=await parseBody(req); if(!b.title || !ROLES.includes(b.accessRole)) return send(res,400,{error:'Укажите название и роль доступа'}); let fileUrl=String(b.url||''), type='link'; if(b.fileBase64 && b.fileName) { const raw=Buffer.from(String(b.fileBase64).split(',').pop(),'base64'); if(raw.length>10*1024*1024) return send(res,400,{error:'Файл больше 10 МБ'}); const fileName=`${Date.now()}_${safeName(b.fileName)}`; fs.writeFileSync(path.join(UPLOADS,fileName),raw); fileUrl=`/uploads/${encodeURIComponent(fileName)}`; type=path.extname(fileName).slice(1)||'file'; } if(!fileUrl) return send(res,400,{error:'Добавьте файл или ссылку'}); const m={id:id('mat'),title:String(b.title),description:String(b.description||''),accessRole:b.accessRole,type,url:fileUrl}; await pool.query('insert into materials(id,title,description,access_role,type,url) values($1,$2,$3,$4,$5,$6)',[m.id,m.title,m.description,m.accessRole,m.type,m.url]); return send(res,201,m); }
      if(method==='PUT' && p.startsWith('/api/admin/applications/')) { const b=await parseBody(req), r=await pool.query('update applications set status=$1 where id=$2 returning *',[String(b.status||'Новая'),p.split('/').pop()]); return r.rowCount?send(res,200,r.rows[0]):send(res,404,{error:'Заявка не найдена'}); }
    }
    return send(res,404,{error:'Не найдено'});
  } catch(e) { console.error(e); return send(res,500,{error:'Ошибка сервера'}); }
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.pdf':'application/pdf','.txt':'text/plain; charset=utf-8','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};
const server=http.createServer(async(req,res)=>{ const url=new URL(req.url,`http://${req.headers.host||'localhost'}`); if(url.pathname.startsWith('/api/')) return api(req,res,url); if(url.pathname.startsWith('/uploads/')) { const user=await auth(req); if(!user) return send(res,401,'Требуется авторизация','text/plain; charset=utf-8'); const name=decodeURIComponent(url.pathname.slice(9)); const r=await pool.query('select access_role from materials where url=$1',[`/uploads/${encodeURIComponent(name)}`]); if(!r.rowCount || (user.role!=='admin' && r.rows[0].access_role!=='common' && r.rows[0].access_role!==user.role)) return send(res,403,'Нет доступа','text/plain; charset=utf-8'); const file=path.resolve(UPLOADS,name); if(path.relative(UPLOADS,file).startsWith('..')||!fs.existsSync(file)) return send(res,404,'Не найдено','text/plain; charset=utf-8'); res.writeHead(200,{'Content-Type':mime[path.extname(file).toLowerCase()]||'application/octet-stream'}); return fs.createReadStream(file).pipe(res); } let file=path.join(PUBLIC,url.pathname==='/'?'index.html':url.pathname.replace(/^\//,'')); if(!file.startsWith(PUBLIC)||!fs.existsSync(file)) return send(res,404,'Страница не найдена','text/plain; charset=utf-8'); res.writeHead(200,{'Content-Type':mime[path.extname(file).toLowerCase()]||'application/octet-stream'}); fs.createReadStream(file).pipe(res); });
initDb().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log(`Альбакор запущен: http://localhost:${PORT}`))).catch(e=>{console.error('Не удалось подключиться к PostgreSQL:',e.message);process.exit(1);});
